# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - name: SonarCloud Scan
#      uses: SonarSource/sonarcloud-github-action@v1.3
#      env:
#        SONAR_TOKEN: 2b4cdc1b2a09b8ed06fe002b2f9fd6c121804ba5 
#      with:
        # Set the sonar.projectBaseDir analysis property
#        projectBaseDir: stream/src # optional, default is .
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file stream/pom.xml
